"""Atoms, geometry, topology, rings, symmetry and synthons for MATRIX."""

from .average_atomic_masses import atomic_mass
from .geometry import MolecularGeometry
from .geometry_io import (
    GeometryParseError,
    detect_qm_output_format,
    normalize_atom_symbol,
    parse_xyz_lines,
    read_enriched_xyz,
    read_geometry,
    read_geometry_with_kind,
    read_xyz,
    read_xyz_atoms_coords,
    write_xyz,
)
from .structure_files import read_mol2, read_molfile
from .inertia import center_of_mass, inertia_tensor, principal_moments
from .isotopes_table import Isotope, get_default_isotope, get_isotope, get_isotopes
from .physical_constants import Phy, get_physical_constants
from .rotational import rotational_constants_MHz
from .symmetry_number import rotational_symmetry_number
from .vibrational import expected_vibrational_mode_count, is_linear_geometry
from .structure import Structure
from .zmatrix import (
    ZMatrix,
    ZMatrixAtom,
    parse_zmatrix_text,
    read_zmatrix,
    zmatrix_to_geometry,
)
from .link import (
    BabelPreprocessResult,
    LinkPreprocessResult,
    SymmetryThresholds,
    electronic_population_overrides_from_xyzin,
    preprocess_to_enriched_xyz,
    read_molecular_symmetry,
    read_symmetry_thresholds,
    write_primitive_coordinate_section,
)
from .primitive_coordinates import (
    MATRIX_XYZ_PRIMITIVES_SCHEMA,
    Primitive,
    PrimitiveCoordinateContract,
    build_primitive_contract,
    build_primitives,
    eval_primitive,
    eval_primitives,
    grad_primitive,
    primitive_b_matrix,
    read_primitive_contract,
    validate_primitive_contract,
    write_primitive_contract,
)
from .accuracy_ladder import (
    AccuracyLadderPlan,
    BackTransformationResult,
    PrimitiveForceFieldResult,
    PrimitiveTarget,
    RefinementLayer,
    ValenceLevel,
    backtransform_primitive_targets,
    apply_accuracy_ladder_plan,
    build_accuracy_ladder_plan,
    build_l1_refinement_targets,
    core_valence_bond_shift,
    evaluate_primitive_force_field,
    target_values_from_plan,
)
from .structural_corrections import (
    BOHR_TO_ANGSTROM,
    CV_EXPONENTIAL_ATOMIC_LOG_AMPLITUDE,
    CV_EXPONENTIAL_PERIOD_DECAY_INV_ANGSTROM,
    CV_RADIAL_COVALENT_RADII_ANGSTROM,
    CV_RADIAL_PERIOD,
    CV_RADIAL_RADIUS_AWARE_PERIOD_LINE,
    CV_RADIAL_SIGMA_SCALE,
    CV_RADIAL_VALENCE_ELECTRONS,
    CV_RADIAL_WEIGHT_THRESHOLD,
    CVExponentialFieldResult,
    CVExponentialPair,
    HydrogenBondContact,
    PairCorrection,
    coordination_switch,
    cv_exponential_pair_parameters,
    cv_radial_bond_delta_angstrom,
    cv_radial_posterior_amplitude_milliangstrom,
    cv_radial_radius_aware_alpha_milliangstrom,
    evaluate_cv_exponential_field,
    hbond_angular_factor,
    perceive_hydrogen_bonds,
    pl1_hbond_delta_angstrom,
    pseudo_bond_pairs,
)
from .primitive_force_field import (
    CHEMICAL_COUPLING_RELATIONS,
    AtomicMMType,
    PrimitiveMMCoupling,
    PrimitiveMMForceField,
    PrimitiveMMType,
    PrimitiveFunctionalParameter,
    PrimitiveFunctionalPolicy,
    SynthonTypingThresholds,
    TorsionFourierParameter,
    TorsionFourierTerm,
    classify_primitive_coupling,
    derive_primitive_mm_force_field,
    evaluate_primitive_functional_parameter,
    evaluate_torsion_fourier_parameter,
    primitive_force_field_bonded_cartesian_gradient,
    primitive_force_field_bonded_cartesian_hessian,
)
from .nonbonded import (
    continuous_electrostatic_pair_components,
    NonbondedHessianComponents,
    UFF_PARAMETER_REFERENCE,
    nonbonded_cartesian_hessian_components,
    nonbonded_cartesian_hessian_correction,
    uff_pair_parameters,
    preferred_atomic_charges_from_xyzin,
    synthon_charges_from_xyzin,
    topology_bonds_from_xyzin,
)
from .continuous_nonbonded import continuous_topology_pair_scales
from .symmetry import (
    MolecularSymmetry,
    SymmetryProjectionDiagnostics,
    SymmetryOperation,
    analyze_molecular_symmetry,
    symmetry_section_lines,
    symmetry_projection_diagnostics,
)
from .validation import (
    MATRIX_XYZ_VALIDATION_SCHEMA,
    ValidationMessage,
    ValidationResult,
    validate_enriched_molecule,
    validation_section_lines,
    write_validation_section,
)
from .topology.atomic_synthons import AtomicSynthons
from .topology.continuous_graph import (
    BondOrderComponents,
    bond_order_components,
    pauling_bond_order,
)
from .topology.contracts import (
    MATRIX_XYZ_FRAGMENTS_SCHEMA,
    MATRIX_XYZ_SYNTHONS_SCHEMA,
    MATRIX_XYZ_TOPOLOGY_SCHEMA,
)
from .topology.pipeline import build_topology_objects
from .topology.observable_comparison import (
    OracleObservableComparison,
    compare_qm_and_geometric_observables,
)
from .topology.snapshot import (
    TOPOLOGY_SNAPSHOT_SCHEMA,
    TopologySnapshotComparison,
    compare_topology_snapshot_entry,
    topology_report_lines,
    topology_snapshot_document,
    topology_snapshot_from_xyzin,
    write_topology_report,
    write_topology_snapshot,
)

__all__ = [
    "AtomicSynthons",
    "BondOrderComponents",
    "GeometryParseError",
    "Isotope",
    "MolecularGeometry",
    "MolecularSymmetry",
    "MATRIX_XYZ_FRAGMENTS_SCHEMA",
    "MATRIX_XYZ_SYNTHONS_SCHEMA",
    "MATRIX_XYZ_TOPOLOGY_SCHEMA",
    "MATRIX_XYZ_VALIDATION_SCHEMA",
    "MATRIX_XYZ_PRIMITIVES_SCHEMA",
    "OracleObservableComparison",
    "AccuracyLadderPlan",
    "AtomicMMType",
    "BOHR_TO_ANGSTROM",
    "CHEMICAL_COUPLING_RELATIONS",
    "BackTransformationResult",
    "Primitive",
    "PrimitiveCoordinateContract",
    "PrimitiveForceFieldResult",
    "PrimitiveMMForceField",
    "PrimitiveMMCoupling",
    "PrimitiveMMType",
    "PrimitiveFunctionalParameter",
    "PrimitiveFunctionalPolicy",
    "NonbondedHessianComponents",
    "PrimitiveTarget",
    "RefinementLayer",
    "ValenceLevel",
    "SynthonTypingThresholds",
    "TorsionFourierParameter",
    "TorsionFourierTerm",
    "CVExponentialFieldResult",
    "CVExponentialPair",
    "HydrogenBondContact",
    "PairCorrection",
    "Phy",
    "BabelPreprocessResult",
    "LinkPreprocessResult",
    "Structure",
    "SymmetryThresholds",
    "SymmetryOperation",
    "SymmetryProjectionDiagnostics",
    "TOPOLOGY_SNAPSHOT_SCHEMA",
    "UFF_PARAMETER_REFERENCE",
    "continuous_topology_pair_scales",
    "TopologySnapshotComparison",
    "ValidationMessage",
    "ValidationResult",
    "ZMatrix",
    "ZMatrixAtom",
    "atomic_mass",
    "build_topology_objects",
    "bond_order_components",
    "pauling_bond_order",
    "compare_qm_and_geometric_observables",
    "build_primitive_contract",
    "build_primitives",
    "build_accuracy_ladder_plan",
    "build_l1_refinement_targets",
    "backtransform_primitive_targets",
    "apply_accuracy_ladder_plan",
    "core_valence_bond_shift",
    "coordination_switch",
    "cv_exponential_pair_parameters",
    "cv_radial_bond_delta_angstrom",
    "cv_radial_posterior_amplitude_milliangstrom",
    "cv_radial_radius_aware_alpha_milliangstrom",
    "derive_primitive_mm_force_field",
    "evaluate_primitive_functional_parameter",
    "evaluate_torsion_fourier_parameter",
    "primitive_force_field_bonded_cartesian_gradient",
    "primitive_force_field_bonded_cartesian_hessian",
    "eval_primitive",
    "eval_primitives",
    "evaluate_primitive_force_field",
    "evaluate_cv_exponential_field",
    "electronic_population_overrides_from_xyzin",
    "expected_vibrational_mode_count",
    "grad_primitive",
    "center_of_mass",
    "compare_topology_snapshot_entry",
    "get_default_isotope",
    "get_isotope",
    "get_isotopes",
    "get_physical_constants",
    "hbond_angular_factor",
    "analyze_molecular_symmetry",
    "inertia_tensor",
    "is_linear_geometry",
    "detect_qm_output_format",
    "normalize_atom_symbol",
    "nonbonded_cartesian_hessian_components",
    "nonbonded_cartesian_hessian_correction",
    "continuous_electrostatic_pair_components",
    "uff_pair_parameters",
    "parse_xyz_lines",
    "principal_moments",
    "perceive_hydrogen_bonds",
    "pl1_hbond_delta_angstrom",
    "pseudo_bond_pairs",
    "preprocess_to_enriched_xyz",
    "preferred_atomic_charges_from_xyzin",
    "read_molecular_symmetry",
    "read_primitive_contract",
    "read_symmetry_thresholds",
    "read_enriched_xyz",
    "read_geometry",
    "read_geometry_with_kind",
    "read_mol2",
    "read_molfile",
    "read_xyz",
    "read_xyz_atoms_coords",
    "read_zmatrix",
    "rotational_constants_MHz",
    "rotational_symmetry_number",
    "parse_zmatrix_text",
    "validate_enriched_molecule",
    "validate_primitive_contract",
    "validation_section_lines",
    "write_validation_section",
    "write_primitive_contract",
    "write_primitive_coordinate_section",
    "write_xyz",
    "symmetry_section_lines",
    "symmetry_projection_diagnostics",
    "synthon_charges_from_xyzin",
    "topology_report_lines",
    "topology_snapshot_document",
    "topology_snapshot_from_xyzin",
    "topology_bonds_from_xyzin",
    "write_topology_report",
    "write_topology_snapshot",
    "zmatrix_to_geometry",
    "primitive_b_matrix",
    "target_values_from_plan",
]
