"""Topology-backed fragment contracts for ORACLE."""

from .contracts import (
    ORACLE_XYZ_ASSEMBLY_SCHEMA,
    ORACLE_XYZ_FRAGMENT_LIBRARY_SCHEMA,
    ORACLE_XYZ_INTERACTION_CENTERS_SCHEMA,
    AtomCenterInteractionRecord,
    FragmentDefinition,
    FragmentContractError,
    FragmentRecord,
    InteractionCenterDefinition,
    InteractionCenterRecord,
    build_fragment_definition_from_xyzin,
    build_interaction_center_definition_from_xyzin,
    fragment_build_section_lines,
    fragment_plan_section_lines,
    interaction_center_section_lines,
    read_interaction_center_definition,
    read_fragment_records,
    validate_fragment_prerequisites,
    write_fragment_build_section,
    write_fragment_electronic_states,
    write_fragment_plan_section,
    write_interaction_center_section,
)

__all__ = [
    "AtomCenterInteractionRecord",
    "FragmentDefinition",
    "FragmentContractError",
    "FragmentRecord",
    "InteractionCenterDefinition",
    "InteractionCenterRecord",
    "ORACLE_XYZ_ASSEMBLY_SCHEMA",
    "ORACLE_XYZ_FRAGMENT_LIBRARY_SCHEMA",
    "ORACLE_XYZ_INTERACTION_CENTERS_SCHEMA",
    "build_fragment_definition_from_xyzin",
    "build_interaction_center_definition_from_xyzin",
    "fragment_build_section_lines",
    "fragment_plan_section_lines",
    "interaction_center_section_lines",
    "read_interaction_center_definition",
    "read_fragment_records",
    "validate_fragment_prerequisites",
    "write_fragment_build_section",
    "write_fragment_electronic_states",
    "write_fragment_plan_section",
    "write_interaction_center_section",
]
