"""Shared QM data sections for MATRIX enriched XYZ containers."""

from .execution_protocol import (
    EXECUTION_PROTOCOL_ID as EXECUTION_PROTOCOL_ID,
    EXECUTION_PROTOCOL_SCHEMA as EXECUTION_PROTOCOL_SCHEMA,
    EXECUTION_PROTOCOL_VERSION as EXECUTION_PROTOCOL_VERSION,
    backend_execution_contract as backend_execution_contract,
    canonical_backend_name as canonical_backend_name,
    load_backend_execution_protocol as load_backend_execution_protocol,
    validate_backend_execution_protocol as validate_backend_execution_protocol,
)
from .method_dialects import (
    BACKEND_METHOD_DIALECTS_ID as BACKEND_METHOD_DIALECTS_ID,
    BACKEND_METHOD_DIALECTS_SCHEMA as BACKEND_METHOD_DIALECTS_SCHEMA,
    BACKEND_METHOD_DIALECTS_VERSION as BACKEND_METHOD_DIALECTS_VERSION,
    backend_method_name as backend_method_name,
    load_backend_method_dialects as load_backend_method_dialects,
    validate_backend_method_dialects as validate_backend_method_dialects,
)

from .capabilities import (
    QM_CAPABILITY_REGISTRY_V2_ID as QM_CAPABILITY_REGISTRY_V2_ID,
    QM_CAPABILITY_REGISTRY_V2_SCHEMA as QM_CAPABILITY_REGISTRY_V2_SCHEMA,
    QM_CAPABILITY_REGISTRY_V2_VERSION as QM_CAPABILITY_REGISTRY_V2_VERSION,
    QMCapabilityRegistryV2 as QMCapabilityRegistryV2,
    QMScientificCapability as QMScientificCapability,
    ScientificCapabilityKey as ScientificCapabilityKey,
    load_qm_capability_registry_v2 as load_qm_capability_registry_v2,
    qm_capability_registry_v2_schema_path as qm_capability_registry_v2_schema_path,
    validate_qm_capability_registry_v2 as validate_qm_capability_registry_v2,
)
from .canonical_resolution import (
    CANONICAL_QM_REQUEST_SCHEMA as CANONICAL_QM_REQUEST_SCHEMA,
    CANONICAL_QM_RUN_SCHEMA as CANONICAL_QM_RUN_SCHEMA,
    BasisAvailabilityUnverified as BasisAvailabilityUnverified,
    CanonicalBasisSetConfirmationRequired as CanonicalBasisSetConfirmationRequired,
    CanonicalQMRequest as CanonicalQMRequest,
    ResolvedCanonicalQMRun as ResolvedCanonicalQMRun,
    canonical_qm_request_from_dict as canonical_qm_request_from_dict,
    canonical_qm_request_schema_path as canonical_qm_request_schema_path,
    canonical_qm_run_schema_path as canonical_qm_run_schema_path,
    resolve_canonical_qm_run as resolve_canonical_qm_run,
    resolve_canonical_qm_run_from_dict as resolve_canonical_qm_run_from_dict,
    validate_resolved_canonical_qm_run as validate_resolved_canonical_qm_run,
)
from .ladder import (
    CANONICAL_QM_LADDER_ID,
    CANONICAL_QM_LADDER_SCHEMA,
    CANONICAL_QM_LADDER_VERSION,
    CanonicalQMLadder,
    canonical_qm_ladder_schema_path,
    load_canonical_qm_ladder,
    validate_canonical_qm_ladder,
)
from .element_policy import (
    QM_ELEMENT_POLICY_ID,
    QM_ELEMENT_POLICY_SCHEMA,
    QM_ELEMENT_POLICY_VERSION,
    AtomElementPolicy,
    FrozenCoreDirective,
    QMElementPolicy,
    ResolvedElementPolicy,
    load_qm_element_policy,
    qm_element_policy_schema_path,
    resolve_element_policy,
    validate_qm_element_policy,
)

from .resources import (
    BACKEND_CAPABILITIES,
    BASIS_ARTIFACT_SCHEMA,
    BSE_BASE_URL,
    DERIVATIVE_POLICIES,
    METHOD_PROFILES,
    QM_CAPABILITY_REGISTRY_SCHEMA,
    QM_SELECTION_SCHEMA,
    PACKAGED_BASIS_REGISTRY_SCHEMA,
    GDV_L1_METHOD,
    GDV_L1_BASIS,
    GDV_L1_ROUTE,
    GDV_L1_CHECKPOINT_ROUTE,
    BackendCandidate,
    BackendRecommendation,
    InitializationHFProvider,
    BasisSetArtifact,
    BasisSetConfirmationRequired,
    BasisSetRequest,
    MethodAlternative,
    QMBackendCapability,
    QMMethodProfile,
    acquire_basis_set,
    basis_set_availability,
    backend_capability,
    backend_capability_registry,
    backend_capability_records,
    basis_format_for_backend,
    basis_set_url,
    method_family,
    packaged_basis_set_path,
    packaged_basis_set_registry,
    qm_capability_registry_schema_path,
    qm_selection_schema_path,
    recommend_qm_backend,
    resolve_open_hf_sto3g_provider,
)


from .surface_fit import (
    LinearConstraint,
    LinearFitDiagnostics,
    LinearFitProblem,
    LinearFitResult,
    fit_linear_surface,
)
from .property_surface import (
    PropertyComponent,
    PropertyEvaluation,
    PropertySurfaceProblem,
    PropertySurfaceResult,
    evaluate_property_surface,
    fit_property_surface,
)

from .hessians import (
    HessianInput,
    canonicalize_hessian_input,
    hessian_input_from_engine,
    supported_hessian_engines,
)
from .normal_modes import (
    HESSIAN_EIGENVALUE_TO_CM,
    CartesianNormalModeSet,
    cartesian_normal_modes_from_hessian,
    mass_weighted_cartesian_hessian,
)

from .sections import (
    ORACLE_XYZ_CARTESIAN_HESSIAN_SCHEMA,
    ORACLE_XYZ_NORMAL_MODES_SCHEMA,
    ORACLE_XYZ_QFF_SCHEMA,
    ORACLE_XYZ_SEMIDIAGONAL_CUBIC_SCHEMA,
    CartesianHessianSection,
    NormalModesSection,
    QFFSection,
    SemiDiagonalCubicSection,
    anharmonic_input_from_qff_section,
    cartesian_hessian_section_from_hessian_input,
    hessian_input_from_cartesian_hessian_section,
    hessian_input_from_xyzin,
    normal_modes_section_from_arrays,
    parse_cartesian_hessian_section,
    parse_normal_modes_section,
    parse_qff_section,
    parse_semidiagonal_cubic_section,
    qff_section_from_anharmonic_input,
    qff_section_from_quartic_force_field,
    quartic_force_field_from_qff_section,
    read_cartesian_hessian_section,
    read_normal_modes_section,
    read_qff_section,
    read_semidiagonal_cubic_section,
    semidiagonal_cubic_section_from_gaussian_data,
    semidiagonal_cubic_section_lines,
    write_cartesian_hessian_section,
    write_cartesian_hessian_section_atomic,
    write_normal_modes_section,
    write_qff_section,
    write_semidiagonal_cubic_section,
)
from .electronic import (
    ORACLE_XYZ_ELECTRONIC_SCHEMA,
    ORACLE_XYZ_ORBITALS_SCHEMA,
    ORACLE_XYZ_TRANSITIONS_SCHEMA,
    ElectronicSection,
    ElectronicStateRecord,
    ElectronicTransitionRecord,
    OrbitalFileRecord,
    OrbitalsSection,
    TransitionsSection,
    electronic_section_lines,
    merge_orbitals_section,
    orbital_file_record_from_path,
    orbitals_section_lines,
    parse_electronic_section,
    parse_orbitals_section,
    parse_transitions_section,
    read_electronic_section,
    read_orbitals_section,
    read_transitions_section,
    transitions_section_lines,
    write_electronic_section,
    write_orbitals_section,
    write_transitions_section,
)
from .properties import (
    ORACLE_XYZ_PROPERTIES_SCHEMA,
    PROPERTY_COLUMNS,
    PropertyComparison,
    PropertiesSection,
    PropertyRecord,
    compare_property_records,
    filtered_property_records,
    merge_properties_section,
    parse_properties_section,
    property_comparison_lines,
    property_comparison_to_dict,
    properties_section_lines,
    properties_summary_lines,
    property_record_to_dict,
    property_records_by_name,
    property_records_for_atom,
    read_properties_section,
    write_properties_section,
)
from .quadrupole import (
    EFG_AU_TO_NQCC_MHZ_PER_BARN,
    QUADRUPOLE_MOMENT_SOURCE,
    QuadrupoleMoment,
    QuadrupoleTensor,
    atomic_number_from_isotope_or_atom,
    efg_asymmetry_parameter,
    efg_to_nqcc_mhz,
    infer_unique_quadrupolar_atom,
    parse_isotope_label,
    quadrupole_moment,
    quadrupole_moment_from_label,
    quadrupole_property_records_from_efg,
    quadrupole_property_records_from_nqcc,
)
from .population import (
    CM5_ALPHA_INV_ANGSTROM,
    CM5_ATOMIC_D,
    CM5_COVALENT_RADII_ANGSTROM,
    CM5_PAIR_D,
    MATRIX_XYZ_QM_POPULATION_SCHEMA,
    QM_POPULATION_SECTION,
    QMPopulationObservables,
    cm5_charges_from_hirshfeld,
    hirshfeld_charges_from_grid,
    mayer_bond_order_matrix,
    mayer_spin_bond_order_matrix,
    parse_qm_population_section,
    population_observables_from_dict,
    qm_population_section_lines,
    read_qm_population_section,
    write_qm_population_section,
)

__all__ = [
    "CANONICAL_QM_REQUEST_SCHEMA",
    "CANONICAL_QM_RUN_SCHEMA",
    "CANONICAL_QM_LADDER_ID",
    "CANONICAL_QM_LADDER_SCHEMA",
    "CANONICAL_QM_LADDER_VERSION",
    "CanonicalQMLadder",
    "CanonicalQMRequest",
    "ResolvedCanonicalQMRun",
    "BasisAvailabilityUnverified",
    "CanonicalBasisSetConfirmationRequired",
    "canonical_qm_request_from_dict",
    "canonical_qm_request_schema_path",
    "canonical_qm_run_schema_path",
    "resolve_canonical_qm_run",
    "resolve_canonical_qm_run_from_dict",
    "validate_resolved_canonical_qm_run",
    "canonical_qm_ladder_schema_path",
    "load_canonical_qm_ladder",
    "validate_canonical_qm_ladder",
    "QM_ELEMENT_POLICY_ID",
    "QM_ELEMENT_POLICY_SCHEMA",
    "QM_ELEMENT_POLICY_VERSION",
    "AtomElementPolicy",
    "FrozenCoreDirective",
    "QMElementPolicy",
    "ResolvedElementPolicy",
    "load_qm_element_policy",
    "qm_element_policy_schema_path",
    "resolve_element_policy",
    "validate_qm_element_policy",
    "LinearConstraint",
    "LinearFitDiagnostics",
    "LinearFitProblem",
    "LinearFitResult",
    "fit_linear_surface",
    "PropertyComponent",
    "PropertyEvaluation",
    "PropertySurfaceProblem",
    "PropertySurfaceResult",
    "evaluate_property_surface",
    "fit_property_surface",
    "EFG_AU_TO_NQCC_MHZ_PER_BARN",
    "ORACLE_XYZ_CARTESIAN_HESSIAN_SCHEMA",
    "ORACLE_XYZ_ELECTRONIC_SCHEMA",
    "ORACLE_XYZ_NORMAL_MODES_SCHEMA",
    "ORACLE_XYZ_ORBITALS_SCHEMA",
    "ORACLE_XYZ_PROPERTIES_SCHEMA",
    "ORACLE_XYZ_QFF_SCHEMA",
    "ORACLE_XYZ_SEMIDIAGONAL_CUBIC_SCHEMA",
    "ORACLE_XYZ_TRANSITIONS_SCHEMA",
    "PROPERTY_COLUMNS",
    "QUADRUPOLE_MOMENT_SOURCE",
    "CartesianHessianSection",
    "CM5_ALPHA_INV_ANGSTROM",
    "CM5_ATOMIC_D",
    "CM5_COVALENT_RADII_ANGSTROM",
    "CM5_PAIR_D",
    "MATRIX_XYZ_QM_POPULATION_SCHEMA",
    "QM_POPULATION_SECTION",
    "HessianInput",
    "HESSIAN_EIGENVALUE_TO_CM",
    "CartesianNormalModeSet",
    "cartesian_normal_modes_from_hessian",
    "mass_weighted_cartesian_hessian",
    "ElectronicSection",
    "ElectronicStateRecord",
    "ElectronicTransitionRecord",
    "NormalModesSection",
    "OrbitalFileRecord",
    "OrbitalsSection",
    "PropertyComparison",
    "PropertiesSection",
    "PropertyRecord",
    "QMPopulationObservables",
    "QFFSection",
    "QuadrupoleMoment",
    "QuadrupoleTensor",
    "SemiDiagonalCubicSection",
    "TransitionsSection",
    "anharmonic_input_from_qff_section",
    "atomic_number_from_isotope_or_atom",
    "cartesian_hessian_section_from_hessian_input",
    "canonicalize_hessian_input",
    "cm5_charges_from_hirshfeld",
    "efg_asymmetry_parameter",
    "efg_to_nqcc_mhz",
    "electronic_section_lines",
    "compare_property_records",
    "filtered_property_records",
    "hessian_input_from_cartesian_hessian_section",
    "hessian_input_from_engine",
    "hessian_input_from_xyzin",
    "hirshfeld_charges_from_grid",
    "infer_unique_quadrupolar_atom",
    "merge_properties_section",
    "merge_orbitals_section",
    "mayer_bond_order_matrix",
    "mayer_spin_bond_order_matrix",
    "parse_qm_population_section",
    "population_observables_from_dict",
    "qm_population_section_lines",
    "read_qm_population_section",
    "normal_modes_section_from_arrays",
    "orbital_file_record_from_path",
    "orbitals_section_lines",
    "parse_cartesian_hessian_section",
    "parse_electronic_section",
    "parse_isotope_label",
    "parse_normal_modes_section",
    "parse_orbitals_section",
    "parse_properties_section",
    "parse_qff_section",
    "parse_semidiagonal_cubic_section",
    "parse_transitions_section",
    "property_comparison_lines",
    "property_comparison_to_dict",
    "properties_section_lines",
    "properties_summary_lines",
    "property_record_to_dict",
    "property_records_by_name",
    "property_records_for_atom",
    "qff_section_from_anharmonic_input",
    "qff_section_from_quartic_force_field",
    "quadrupole_moment",
    "quadrupole_moment_from_label",
    "quadrupole_property_records_from_efg",
    "quadrupole_property_records_from_nqcc",
    "quartic_force_field_from_qff_section",
    "read_cartesian_hessian_section",
    "read_electronic_section",
    "read_normal_modes_section",
    "read_orbitals_section",
    "read_properties_section",
    "read_qff_section",
    "read_semidiagonal_cubic_section",
    "read_transitions_section",
    "semidiagonal_cubic_section_from_gaussian_data",
    "semidiagonal_cubic_section_lines",
    "supported_hessian_engines",
    "transitions_section_lines",
    "write_cartesian_hessian_section",
    "write_cartesian_hessian_section_atomic",
    "write_electronic_section",
    "write_normal_modes_section",
    "write_orbitals_section",
    "write_properties_section",
    "write_qff_section",
    "write_semidiagonal_cubic_section",
    "write_qm_population_section",
    "write_transitions_section",
    "BACKEND_CAPABILITIES",
    "BASIS_ARTIFACT_SCHEMA",
    "BSE_BASE_URL",
    "DERIVATIVE_POLICIES",
    "METHOD_PROFILES",
    "QM_CAPABILITY_REGISTRY_SCHEMA",
    "QM_SELECTION_SCHEMA",
    "PACKAGED_BASIS_REGISTRY_SCHEMA",
    "GDV_L1_METHOD",
    "GDV_L1_BASIS",
    "GDV_L1_ROUTE",
    "GDV_L1_CHECKPOINT_ROUTE",
    "BackendCandidate",
    "BackendRecommendation",
    "InitializationHFProvider",
    "BasisSetArtifact",
    "BasisSetConfirmationRequired",
    "BasisSetRequest",
    "MethodAlternative",
    "QMBackendCapability",
    "QMMethodProfile",
    "acquire_basis_set",
    "basis_set_availability",
    "backend_capability",
    "backend_capability_registry",
    "backend_capability_records",
    "basis_format_for_backend",
    "basis_set_url",
    "method_family",
    "packaged_basis_set_path",
    "packaged_basis_set_registry",
    "qm_capability_registry_schema_path",
    "qm_selection_schema_path",
    "recommend_qm_backend",
    "resolve_open_hf_sto3g_provider",
]
